=begin
#ClickSend v3 REST API

# This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AccountApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountApi' do
    it 'should create an instance of AccountApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountApi)
    end
  end

  # unit tests for account_get
  # Get account information
  # Get account details
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'account_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_post
  # Create a new account
  # Create An Account
  # @param account Account model
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'account_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_verify_send_put
  # Send account activation token
  # Send account activation token
  # @param account_verify Account details
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'account_verify_send_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for account_verify_verify_by_activation_token_put
  # Verify new account
  # Verify new account
  # @param activation_token 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'account_verify_verify_by_activation_token_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for forgot_password_put
  # Forgot password
  # Forgot password
  # @param username Username belonging to account
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'forgot_password_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for forgot_password_verify_put
  # Verify forgot password
  # Verify forgot password
  # @param verify_password verifyPassword data
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'forgot_password_verify_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for forgot_username_put
  # Forgot username
  # Forgot username
  # @param email Email belonging to account
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'forgot_username_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
