=begin
#ClickSend v3 REST API

# This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ContactListApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactListApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ContactListApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactListApi' do
    it 'should create an instance of ContactListApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ContactListApi)
    end
  end

  # unit tests for lists_by_list_id_delete
  # ListsByListIdDelete
  # Delete a specific contact list
  # @param list_id List ID
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'lists_by_list_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lists_by_list_id_get
  # Get specific contact list
  # Get specific contact list
  # @param list_id List ID
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'lists_by_list_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lists_by_list_id_put
  # Update specific contact list
  # Update specific contact list
  # @param list_id Your list id
  # @param list_name Your new list name
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'lists_by_list_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lists_get
  # Get all contact lists
  # Get all contact lists
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :limit Number of records per page
  # @return [String]
  describe 'lists_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lists_import_by_list_id_post
  # Import contacts to list
  # Import contacts to list
  # @param list_id Your contact list id you want to access.
  # @param file ContactListImport model
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'lists_import_by_list_id_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lists_post
  # Create new contact list
  # Create new contact list
  # @param list_name Your contact list name
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'lists_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for lists_remove_duplicates_by_list_id_put
  # Remove duplicate contacts
  # Remove duplicate contacts
  # @param list_id Your list id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'lists_remove_duplicates_by_list_id_put test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
