=begin
#ClickSend v3 REST API

# This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MasterEmailTemplatesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MasterEmailTemplatesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MasterEmailTemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MasterEmailTemplatesApi' do
    it 'should create an instance of MasterEmailTemplatesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MasterEmailTemplatesApi)
    end
  end

  # unit tests for master_email_template_categories_get
  # Get all master email template categories
  # Get all master email template categories
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :limit Number of records per page
  # @return [String]
  describe 'master_email_template_categories_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for master_email_template_category_get
  # Get specific master email template category
  # Get specific master email template category
  # @param category_id Email category id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'master_email_template_category_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for master_email_template_get
  # Get specific master email template
  # Get specific master email template
  # @param template_id Email template id
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'master_email_template_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for master_email_templates_get
  # Get all master email templates
  # Get all master email templates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :limit Number of records per page
  # @return [String]
  describe 'master_email_templates_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for master_email_templates_in_category_get
  # Get all master email templates in a category
  # Get all master email templates in a category
  # @param category_id Email category id
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :limit Number of records per page
  # @return [String]
  describe 'master_email_templates_in_category_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
