=begin
#ClickSend v3 REST API

# This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/clicksend-api/clicksend-codegen.git
ClickSend Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for ClickSendClient::PostDirectMailApi
# Automatically generated by clicksend-codegen (github.com/clicksend-api/clicksend-codegen)
# Please update as you see appropriate
describe 'PostDirectMailApi' do
  before do
    # run before each test
    @instance = ClickSendClient::PostDirectMailApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostDirectMailApi' do
    it 'should create an instance of PostDirectMailApi' do
      expect(@instance).to be_instance_of(ClickSendClient::PostDirectMailApi)
    end
  end

  # unit tests for post_direct_mail_campaigns_get
  # Get direct mail campaigns
  # Get direct mail campaigns
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :limit Number of records per page
  # @return [String]
  describe 'post_direct_mail_campaigns_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_direct_mail_campaigns_price_post
  # Calculate direct mail campaign price
  # Calculate direct mail campaign price
  # @param post_direct_mail PostDirectMail model
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'post_direct_mail_campaigns_price_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_direct_mail_campaigns_send_post
  # Send direct mail campaign
  # Send direct mail campaign
  # @param post_direct_mail PostDirectMail model
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'post_direct_mail_campaigns_send_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_direct_mail_locations_search_by_country_get
  # Search for a location
  # Search for a location
  # @param country Country Code to search
  # @param q Search term (e.g. post code, city name)
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :limit Number of records per page
  # @return [String]
  describe 'post_direct_mail_locations_search_by_country_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
