=begin
#ClickSend v3 REST API

# This is the official [ClickSend](https://clicksend.com) SDK.  *You'll need to create a free account to use the API. You can register [here](https://www.clicksend.com/signup).*  You can use our API documentation along with the SDK. Our API docs can be found [here](https://developers.clicksend.com). 

OpenAPI spec version: 3.1.0
Contact: support@clicksend.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ReferralAccountApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReferralAccountApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ReferralAccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReferralAccountApi' do
    it 'should create an instance of ReferralAccountApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ReferralAccountApi)
    end
  end

  # unit tests for referral_accounts_get
  # Get all referral accounts
  # Get all referral accounts
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [Integer] :limit Number of records per page
  # @return [String]
  describe 'referral_accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
